### ISSUE TITLE
configuration: support several splunk servers and define their roles

### ISSUE THREAD

**Issue by K-Yo** [K-Yo/splunk_exporter#27]
idea:

```yaml
instances:
  - address: splunk-idx.local
    token: thisisthetoken
    roles: [idx]
    insecure: true # defaults to false
  - address: splunk-sh.local
    token: anothertoken
    roles: [sh, idx]
    insecure: true
    metrics: [] # metrics as previously, but they will be searched on this instance
```

Document for each roles, the necessary (splunk) capabilities to scrape the instance.

### Search Tier

- `search_head`

### Indexing Tier

- `indexer`
- `cluster_manager`

### Collection Tier

- `universal_forwarder`
- `heavy_forwarder`

### Management

- `license_manager`
- `deployment_server` (DS)
- `deployer` (SHC-D)
- `monitoring_console` (MC)

### Cloud specific instances

- which?
