### ISSUE TITLE
support configuration to export all metrics from one splunk index

### ISSUE THREAD

**Issue by K-Yo** [K-Yo/splunk_exporter#7]
grab all metrics from one index
```yaml
index: "_metrics"
all_metrics: true
```

or list specific metrics (default for all_metrics should be false)
```yaml
index: "_metrics"
metrics:
  - "a"
  - "b"
```
